# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for a list of available hooks
ci:
   autofix_prs: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        args: ['--markdown-linebreak-ext=md']
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
